language: go
sude: false
go:
  - 1.6
  - 1.8
  - 1.10
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install: make get-deps
script:
  - make test
  - make cover
  - $GOPATH/bin/goveralls -coverprofile=coverage.all.out -service=travis-ci