language: go
sude: false
go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install: make get-deps
script:
  - make all
  - $GOPATH/bin/goveralls -coverprofile=coverage.all.out -service=travis-ci